### ISSUE TITLE
[0.9 staging-1515] Advanced Culinary Research should require Cooking or Baking, not both at the same time

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1060]
During our latest test server run we had some issue with CO2 levels which caused our main baker to wait out everyone panicking about the temperature, etc. Because of this our main cook couldn't advance into Advanced Cooking - everything was lined up, except for the Advanced Culinary Research papers. Those papers have two recipes, both of which require input from both a Cook and a Baker. Perhaps it would be nicer if either of those two professions could produce them, rather than both. The recipes could take either a Salad and Simmered Meat, or a Baked Vegetable and Baked Meat. This way both of those professions could contribute the Advanced Research without relying on the other.

**Comment by D3nnis3n** [comment]
The interconnection of recipes, especially the reyling on others is an intended feature. One thing we want to do is to improve this to make Eco include much more supplying to other professions. The tension as of CO2 is a actually a good example of why talking is required, as you otherwise cannot progress easily. Methods need to be found to fix the issue itself, not introducing a workaround.
