### ISSUE TITLE
[0.9] Give Roads the Ramp building components from Ashlar buildings

### ISSUE THREAD

**Issue by ThePiachu** [StrangeLoopGames/EcoSuggestions#1097]
It's really nice that the T4 buildings have such a variety of shapes that can be crafted:

![image](https://user-images.githubusercontent.com/964559/80434702-58482980-88af-11ea-975c-25c768d3d915.png)

It would be nice if we saw some of the shapes used in other places as well, such as the Ramp A-D for building road ramps instead of the prefab ramps. I often found myself wanting to start building ramps from the back down, and being able to select which part to construct would help with that.

Also, if we had the option to build lines of Roads using the Hammer, that would be an extra benefit!

A little related to #1052

**Comment by Engimage** [comment]
Roads are already like that in new builds, just get to see them (Ramp A-D)
Other shapes make no sense for roads as you won't be able to drive on those anyways.

**Comment by trickenso** [comment]
Small though: There is limited utility in placing one segment of a road ramp at a time, since I can't imagine many instances of need a single segment of ramp. It might get fiddly if every ramp required you to place four individually-selected blocks.

Placing them like you would a line of wall, or stamping the ramp into four blocks with a road tool, as you would a line of dirt road would be ideal, and avoid a lot of scrolling and clicking to select exactly the right ramp segment.

**Comment by ThePiachu** [comment]
You could place a line of road segments at a time, so if you're building a 5-wide ramp you can lay them down 5 across, then switch to the other shape and lay that line.

**Comment by trickenso** [comment]
Or place the whole 5x4 area at once... My point is that there's no particular reason to allow us to place the ramp segments individually.

Unless there's a use case I've not thought of where a particular part of a road ramp might want to exist in isolation.

**Comment by elfl0rd** [comment]
> need a single segment of ramp

Road bump, decoration, borders, etc.

**Comment by trickenso** [comment]
> Road bump, decoration, borders, etc.

These make sense - good to confirm the cases exist. I guess I just figured this kind of thing wouldn't necessarily be build using road blocks, which was foolish of me. Road bumps particularly make perfect sense.

In that case, would there also be utility in being able to place a 'complete' ramp at once, for when you just want to lay a road, rather than selecting each piece individually every time?
I guess at that level it's just a quality of life feature.

**Comment by elfl0rd** [comment]
When you build a wide road, you can build lines one block at a time.
Already for a road width of 4 blocks, the number of actions becomes almost the same as when building with ramps.
Perhaps building ramps by area would be convenient, but it would require complex background mechanics, and from the simple options (build by blocks or build by ramps) I personally will choose blocks.

**Comment by trickenso** [comment]
> Already for a road width of 4 blocks, the number of actions becomes almost the same as when building with ramps.

This seem to be assuming you're laying the blocks across the width of the road, not along its length. If you're laying blocks longitudinally the road blocks would be significantly quicker to place than laying ramps block by block.

> Perhaps building ramps by area would be convenient, but it would require complex background mechanics

Agreed

> from the simple options (build by blocks or build by ramps) I personally will choose blocks

I honestly can't imagine I will ever want to place anything other than a complete ramp - understood that others will have other preferences.

Totally want to avoid having to prefabricate ramps at a table and carry them to their use point when it doesn't make much sense, but it still seems odd to have to select and place four different kinds of blocks if the vast majority of the time you'll be laying a complete ramp.

Much rather place blocks in situ over prefabricating ramps at a table, certainly.

**Comment by D3nnis3n** [comment]
This has been implemented a while ago, hence I'm closing this issue.
