### ISSUE TITLE
Steam engine train and cars

### ISSUE THREAD

**Issue by Muzzleburn** [StrangeLoopGames/EcoSuggestions#1331]
So I find it tiring on the long hauls with trucks back to my main town going back and forth and takes many loads and I know that we can build steel and iron and you already have steam engines so I was just wondering how hard it would be to add the ablilty to lay track and build a steam engine train and cars? on my Facebook group I've talked it over with the others that play eco and we all would like to see something like a steam train and cars thank you for your time hope you find this as exciting as I did!
(picture for effect)

![steam engine](https://user-images.githubusercontent.com/75749508/101666323-af9ca380-3a13-11eb-94f8-c559ddec61c8.jpg)

**Comment by PixlRainbow** [comment]
maybe a bus too while we're at it lol
A bus would be a compromise between trains and cars; carries more than a car, but less than a train, but doesn't need tracks.

**Comment by JestinJae** [comment]
I suppose "hard" would be a relative thing, but to get the general idea across.  To add trains they would have to add the concept of rails.  Which would basically be an entity following a set of blocks.  One issue with this would be how to make a "curve", since presently most things are based around the basic block entity.  So its possible that this would also require a new placement coordinate system instead of the block-coordinates which I suspect are used now.  I know in player/animal/vehicle terms there is already a more fine-grained coordinate system.

All of that aside, I would love to have trains in the game, but perhaps tractor-trailers would be more practical with the current tech. I say that, but then as I type it I wonder how hard it would be to tether two objects together around a hinge and factor in walls and things for turning etc...could also be a pain *sigh*.

**Comment by PixlRainbow** [comment]
> One issue with this would be how to make a "curve", since presently most things are based around the basic block entity.

afaik in Factorio (a 2D factory building game with a grid tile system) curves in rails were implemented as extra-large "machines"  that were more than 1 tile wide, with overlapping hitboxes:
![image](https://user-images.githubusercontent.com/44422178/107006300-e7358b00-67cb-11eb-99ee-72c56fd3e0ea.png)


> perhaps tractor-trailers would be more practical with the current tech. I say that, but then as I type it I wonder how hard it would be to tether two objects together around a hinge and factor in walls and things for turning etc...could also be a pain sigh.

aren't there already tractor attachments ingame? I.e. the Steam Tractor Plough, Steam Tractor Sower, Steam Tractor Harvester?

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1571
