### ISSUE TITLE
Suggestion: Bicycle

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#134]
_From @Xeanoa on April 14, 2018 20:52_

A small vehicle 1x2x2, without storage, that increases movement speed, has moderate restrictions on travel, good turn rate, and higher movement speed, and calorie consumption similar to running maybe?

Walking around is one of the more wasteful tasks in the game, and cutting that time down while generating a fun way to travel seems like a good idea to me.

_Copied from original issue: StrangeLoopGames/EcoIssues#7196_

**Comment by BlazeGuy2** [comment]
_From @Dreepa on April 15, 2018 12:1_

I had the same thought. In terms of world balancing, I find the game is far from the sweet spot. 
Creating bigger worlds makes game-play slow and distances travelled can get annoying. 

There are many minecraft mods dealing with this problems, introducing a progression for character attributes like jump height, running speed, etc.
It feels really good. In the start you are more limited, but then you get running boots and eventually jet-packs and teleports. Not saying ECO should do that, just a reference for good scaling of player-tools.
It makes you feel like you advance, and it has real impact on how much time you spend on diferent activities. Running long distances back and forth is nice as long as it is new only (or while you explore new areas).

**Comment by BlazeGuy2** [comment]
_From @talamatur on April 18, 2018 16:5_

see this related suggestion of motorcycles https://github.com/StrangeLoopGames/EcoIssues/issues/7264

**Comment by SatsukiShizuka** [comment]
Since we have tractors with modules as part of the code now, recommend that we:
- Enable small wood cart and wood cart to be attachable parts to the bicycle, offering a weight and small speed upgrade to the wood cart (faster than walking, slower than steam truck), performs like any other vehicle (requiring slopes).
- The bicycle should be made of wrought iron (since rattan is not available XD) and preferably ALSO made at the assembly line, albeit at a much lower tech (and material/skill) requirement than the steam truck. Perhaps this can be the thing engineers can practice their craft with, or upgrade wood carts to extend their effective lifetime for newer/poorer players.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1264
