### ISSUE TITLE
Improvement: Implement storage capacity check on shop buy orders

### ISSUE THREAD

**Issue by PhoenixBirdWingQc** [StrangeLoopGames/EcoSuggestions#1493]
It's SUPER annoying when a store has a buy order for a specific or unlimited quantity of an item, but the store's linked storage capacity doesn't accommodate the desired quantity. 

This is frequently an issue that costs players significant amounts of play time. A player will see a buy order (e.g. from global map) for a certain (or unlimited) quantity of an item; they'll drag the resources to the shop (e.g. some times across the entire world) and get there only to find that the linked storage units are all full and the items cannot be sold to the store. Then the player can either dump the items on the ground or lug them all the way back home. This is especially annoying during early game, where large amounts of heavy resources have to be transported via wooden cart. Time is wasted in transit, but may also be wasted in crafting and resource collecting leading up to the (failed) sale to the store.

Can the store system be modified to accommodate the following 'use case' (or ones similar in spirit) :
1. Store owner creates buy order for finite or infinite quantity of ITEM_A
2. Actual/displayed quantity for buy order of ITEM_A is overwritten with MIN(max. available linked storage capacity for ITEM A, user-entered quantity)
3. Customer #1 sells some quantity of ITEM_B to the shop
4. Actual/displayed quantity for buy order of ITEM_A is re-computed according to, MIN(max. available storage capacity for ITEM A, user-entered quantity)
5. Customer #2 opens the shop info (e.g. from global map) and sees the quantity of ITEM_A that can actually be bought by the shop (i.e. with storage capacity considered)

It might not be as simple as that, and it may not solve all inconveniences associated with a store's linked storage being filled - but as far as I've thought through alternative scenarios and corner cases, this seems like it only presents QoL benefits, while introducing no disadvantages.

**Comment by D3nnis3n** [comment]
Hello,
thank you for your suggestion.

We have considered and tried to implement such a check before as we do agree it would be useful, but unfortunately in all cases it lead to a massive performance hit to calculate these informations so that the result was no longer worth the performance hit. Currently, there is no performance-efficient way to do this and hence we do not plan an implementation of this. We might revisit that in the far future, but for now this unfortunately is not an option, hence I'm closing the suggestion.
