### ISSUE TITLE
Make hunting exciting with a few changes

### ISSUE THREAD

**Issue by 1ntrospect1on** [StrangeLoopGames/EcoSuggestions#1662]
With quite few changes, hunting as a profession can be made alot more fun and exciting.

For a start, i suggest 

- _Removing the laser crosshair. Make it fluctuate slightly with breath._ The better bow, the less sway.
- Make the animals slightly more aggressive. not completely combative, just always defend themselves when attacked.
- Double the speed of the alligator, it's too easy and slow.
- Double the damage to your stamina from animal attacks. Or perhaps another soundeffect when you are bitten, like a moan. Calorie damage doesn't change the game at all, just there to give a sense of urgency.

Any improvement on desync would improve hunting alot. Desync with animals is super frustrating when hunting.

**Comment by D3nnis3n** [comment]
The whole suggestion goes into the direction of making animals more 'defensive' - we have noticed though that the vast majority of our players does not wish for that to happen and had to tone down mechanics similar to that that we had already in order to make people happy again. We hence don't currently have plans to go into the opposite direction again. We've also been made aware by several people that most of the animals in our game do not show aggressive behaviour, even when attacked - as such the representation we had not being sustainable scientifically.

The crosshair as the only suggestion not going into that direction is becoming a talent in the future.

As such I'm closing this suggestion.
