### ISSUE TITLE
Balance research books by giving servers flexibility

### ISSUE THREAD

**Issue by 1ntrospect1on** [StrangeLoopGames/EcoSuggestions#1667]
Right now a researchbook contains infinite pages. So every serverpopulation only has to make 1 book per specialization, and they are set for the game, granted they print pages and share.

I suggest introducing some _flexibility_, by making it a _server-option_ whether a research book contains 1, 3, 5, 10, or infinite pages, instead of _only_ containing infinite pages as it is now. 

Default can remain infinite pages. Introducing flexibility here, would spare servers for relying on a mod.

**Comment by D3nnis3n** [comment]
As a team we have decided that we want to stress knowledge as a resource that 'stays' and should be freely available. I'm very well aware that this does not work with every server concept out there, given White Tiger does deviate from that specifically for a special economy focus, but our main goal with options is to introduce them where we consider any option you could set to be within the games design and maintanable for us.

For this setting that is not the case, given we have a clear internal opinion towards it. We generally incentivize modders and using mods, though and altering research to fit into the economical concepts via mods is extremely easy (you could for example just let people craft 5 skill scrolls for the cost of a book) and typically compatible with Updates as well when done with overrides, so there isn't really a need to introduce such a setting to support economically focused concepts either. As a matter of fact, the skill scroll modification on White Tiger is the only one that did not have to be updated a single time since it's introduction in Update 9.

With skill scrolls no longer giving Land Claim Papers in 10.0 the meaning of research also is even more focused on just knowledge, not economically valuable items, which is why it's rather unlikely this would ever make it to the game. So I'm closing this suggestion.
