### ISSUE TITLE
Drink + Electorlytes

### ISSUE THREAD

**Issue by CTH999** [StrangeLoopGames/EcoSuggestions#1677]
Now, of course, with improved water, you need to drink, not to mention keep your electrolytes in ballance!
1. Water: Taken from [streams ](https://github.com/StrangeLoopGames/EcoSuggestions/issues/1676)and [oceans](https://github.com/StrangeLoopGames/EcoSuggestions/issues/1676)
2. Can make you [sick](https://github.com/StrangeLoopGames/EcoSuggestions/issues/1678)
3. Salt Water adds to Electrolytes
4. Take ocean water to increase electrolytes drasticly
5. Steam water has less effect on electrolytes
6. filter ocean water to remove infectious agents and too many electrolytes
7. filter freshwater to remove infectious agents
8. make distilled water for some poupuses (Future automation?)
9. distilled water _decresease_ electrolytes
10. With more advanced technology, manipulate whats in the water, makeing targeted electrolytes and minerals
11. Certain foods (Especially fruits) have large quantities of naturally-filtered water, and help balence minerals and electrolytes
12. Some foods can be juiced, or ground into smoothies
13. Unbalence Electrolytes mess with the [Immune System](https://github.com/StrangeLoopGames/EcoSuggestions/issues/1678)
14. Water from different places has different composistion
15. Location of growth might effect plant mineral contents?

**Comment by MystLeissa** [comment]
While I like these ideas, let me just reiterate, too much simulation of realism is probably bad for bigger servers which already struggle with things like mere hunger rates. Also fact is it's not a life simulator, I would very much like to see a drink system, but electrolights may be carrying it too far; more over, I have no idea what benefits (buffs) could be justified by drinking (especially since you can't die in Eco, nor would I be in favor of adding such a system.)

**Comment by CTH999** [comment]
yeah, true...
