### ISSUE TITLE
Electric Smelter

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#201]
_From @ProFatBoi on March 15, 2018 12:31_

Would be good to eventually be able to create an electric smelter which didn't cause any pollution.

The tailings are starting to take up alot of space and the Blast Furnace creates alot of air pollution.

_Copied from original issue: StrangeLoopGames/EcoIssues#6083_

**Comment by BlazeGuy2** [comment]
_From @Huntermeign on March 15, 2018 14:42_

It would but if you think about it unless you have a lot of wind mills powering it all you're really doing is burning coal from a generator to power the smelter. Actually that is a good idea. It can show people different needs for different power sources.

**Comment by BlazeGuy2** [comment]
_From @ProFatBoi on March 15, 2018 14:50_

It would start bringing in the need for things like solar farms and wind farms. Would just need some sort of substation and powerlines to transfer the power to the village.

Finally got a factory up and running yesterday and built a Combustion generator to power it. The rate it was eating through the petrol and coal was ridiculous and was chucking out alot of pollution. So shut it down and built two solar panels to power it.

**Comment by trevelmike** [comment]
with the amt of smelting just get rebars and especially since it now costs two steels for every damm rebar which frankly is ridiculous, i would want an electric blast furnace, cement kiln among others. Making charcoal is terrible. For instance i chopped down an old growth redwood or redwood. Gave me about 400 or so logs but them i turn it into lumber uses 200 of those logs and out of 100 lumber i get a mere 30 charcoal. Items need to be reduced in cost esp those that require multiple divisions. It is ridiculous at this point how much iron coal etc just to make steel then rebar all because that electric machinist table require tier 3 mats. There even more pollution from that cement kiln.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/201
