### ISSUE TITLE
Treasury - Donate and/or one time tax

### ISSUE THREAD

**Issue by elfl0rd** [StrangeLoopGames/EcoSuggestions#447]
After removing negative allocation, there is no way to fast fill it. (law, swiching tax% is not good to use)
And no way to "penalty" wrong player actions.

Please, add "tax" button to treasury, it's make leader more free!

**Comment by Sekor2600** [comment]
Or when Player are Long Offline and dont come Back

**Comment by Deantwo** [comment]
I would rather want to see `/pay treasury,<amount>,<currency>` allowed.
Or if magic values are no-go make a `/donate <amount>,<currency>` to give the treasury money.

Being allowed to actively take from players will just be used for greif...

If you want to take money from offline players, it would be better if it has to be a law that everyone has a chance to vote on.
For example if we got some more "hours since last online" law options. So we can implement "long time offline tax" laws.

**Comment by elfl0rd** [comment]
Server leader can easy grief by setting taxes 1000%...

**Comment by MarjieAVolk** [comment]
> Currently:
> Treasury is filled through tax setting.
> 
> Problem:
> In order to fill the treasury, we had to announce to players to stop doing direct transaction for a moment. We then cranked up the taxes to 100%, direct-transfered money between 2 player back and forth (filling the treasury) and then set tax low again.
> 
> Suggestion:
> Unless I have just missed the function somewhere... Add the ability for player to donate to the treasury directly. Maybe just through /pay 'Treasury',[Amount],[Currency]
-- @Dreepa (copied from https://github.com/StrangeLoopGames/EcoIssues/issues/6998)

**Comment by pamduncan** [comment]
The treasury should be filled by taxation not just arbitrarily decided to quickly fill it by taking players money.  Negative allocation quickly became a terrible means of ways to drive people off a server that were not liked for personal reasons and not game play reasons.  It was a quickly mis-used mechanic as a player could be penalized without anyway to prove they had not done anything to be penalized for and those that had worked hard and earned money were being negative allocated just because they had more money.    If a player is found to have broken a law that the public has voted on, and not something that a leader has just decided on in their head without a vote, then the option should be that they pay the fine that is levied.  Since there is not really a court system set up yet penalizing people is not really a game mechanic and one has to wonder if doing things like hitting someone with a fine because they cannot play every day or more than once a week is really a good way to build a community

This is also why I think its wrong that every player can see every other players account and exactly how much money they have.   In real life your bank account and personal finances are your business and are not public knowledge.  If you don't have the money you need to pay for something you ordered then you should get negative reputation for that - not get denied the start of the item because the person you ask to build it can see you do not have the money in your pocket right them - while you may very well have it when it comes time to pay and are just ordering it now so when you have the money its ready.

**Comment by LiaungYip** [comment]
As a currency minter / server leader, I've manually filled the Treasury by creating a tax law triggered by a very specific (unusual) action, then performing that action repeatedly.

i.e. Pass a law that taxes a player $1,000, when placing a Copper Pipe block, on a specific 1×1 plot property, called "Special Tax Gathering Place", which only I have permissions on.

Once the law passes - `/passlaws` is helpful - the player with the money gets a Copper Pipe, and places it down in the "Special Tax Gathering Place". This causes them to "donate" $1,000 to the Treasury each time they place the Copper Pipe. The action is repeated until the Treasury has enough money in it.

A player can only perform this action if they are authorized on the "Special Tax Place" property, so there are no side effects on other players.

----

Aside, not directly relevant to the feature request,

@pamduncan:

> The treasury should be filled by taxation not just arbitrarily decided to quickly fill it by taking players money. 

I'm not sure that "arbitrarily taking a player's money" or "arbitrarily punishing a player" is the intended use case here.

The intended use case would be for a player, who has just minted $1,000 of coins, to give $500 of those coins to the Treasury. This helps jump-start the effectiveness of laws that allocate money for positive actions.

> This is also why I think its wrong that every player can see every other players account and exactly how much money they have. In real life your bank account and personal finances are your business and are not public knowledge. If you don't have the money you need to pay for something you ordered then you should get negative reputation for that - not get denied the start of the item because the person you ask to build it can see you do not have the money in your pocket right them - while you may very well have it when it comes time to pay and are just ordering it now so when you have the money its ready.

Eco isn't real life.

**In real life, private purchasers (like you and I) are either a) present at the instant they decide to spend money,** or b) **have a guaranteed line of credit**, i.e. a credit card.

**This doesn't work in Eco, because the purchaser isn't always online, and there is no concept of purchase on credit.**

Recall that [one of Eco's main design goals](https://www.strangeloopgames.com/eco-blog-5-how-the-player-run-economy-works/) is to enable trading between players who aren't online at the same time.

> By allowing sale of goods and services while offline through store interfaces, we allow players to interact through trade even when they’re not online at the same time. This is essential for an online game played by many people, and will allow large-scale organization of sophisticated projects requiring the contribution of many specialized laborers. That’s exactly what’s needed to build the technology needed to prevent global catastrophes in Eco, so the world’s survival and your own really depends on your ability to function efficiently within the economy.

Trading between players who are offline can only work if suppliers can see what orders are open for fulfilment, **and** if the purchaser has enough money to pay.

No-one is interested in "punishing" or "giving negative reputation to" players who "can't pay their debts", since no debt ever arises - Eco won't let you buy or sell goods, or contracted services, that you don't have enough money to cover. **Eco won't let you create a debt, unless you specifically agree to borrow or lend money as part of a contract.**

The reason suppliers need to know the currency balance of other players is so **they can figure out how best to satisfy the purchaser's needs, within the limits of the purchaser's budget.** This sort of constructive offline trading is what makes Eco's economy work when players are in different timezones or different schedules, and can't check each other's bona fides in real time.

The alternative I think you're suggesting - which is that all players bank balances should be secret, and players should only have open buy orders if they can afford to pay for fulfilment of **all orders simultaneously** - allows for far less flexibility. It would be interesting as a mod, but I don't know if I would recommend secret bank balances as the default setting.

I have seen the problems that you are suggesting - that rich players are penalised for being rich. The problem here is that a large part of the money supply gets tied up with one or two players, and the currency loses liquidity. It becomes difficult to buy or sell because there's not enough money in circulation.

At this point, the usual response is to ask the rich player what goods or services they would like, in exchange for some of their money - the economy working as designed! 

In the alternative game rules, where all bank balances are secret, the problem still exists, except no-one knows where the money is.

**Because the bank balances are secret,  no-one can figure out whose needs they should be trying to meet, to earn the money back.**

The obvious solution is to print more money, but that only delays the problem to the future - the money will still accumulate with players who sell more than they buy.

----

We should recognise that Eco simulates **some, but not all** aspects of real life. Secret bank balances are realistic, but Eco's economy would not work if it was fully realistic. Eco's co-operative economy is at its best when players contribute according to economic signals, including a) what other players are buying, b) how much of it they can buy at that moment, and c) do that while other players are offline, and can't actively monitor their money supply.

**Comment by D3nnis3n** [comment]
I do agree with elfl0rd. The ability to tax (or for my case "fine") a player should definatley be there. I see the concerns about griefing, but that is also possible with the tax percentage setting easily, especiallyas the tax change is announced a bit later than it happens - around a minute.

The taxing of single persons though is a very useful tool to enforce laws and rules that are not possible by laws. E.g. for traffic offenses. A relevant problem on my server is people letting stand their carts in the public roads when logging off. For now i ask them to pay, most do, those that don't will have a claim paper less. Those are workarounds. On our server noone would misuse that and even if they would i would consider it griefing and ban the person. But for servers with active admins this is a feature that is fully fine. I'm really sad that this feature was already there earlier.

Now with the loans, that people can just not pay back this will have another use: Seizing the loan and giving it over to the guy lending it out after a judge ruling. I can see this feature may not be suitable for all or unadministrated servers but taxes and rules are part of the game and they players are free to choose a server that keeps griefers away.
