### ISSUE TITLE
Critical Bug - Game Broken Due To Requirement Loop for Oil Refinery

### ISSUE THREAD

**Issue by SnarkyBird** [StrangeLoopGames/EcoSuggestions#460]
So, with the recent beta release, I was in the process of getting my electronics and machine labs up and running on our server.  Need a robot assembly line to make an oil refinery, because I need plastic to make fiberglass.  

Need servos to make an oil refinery.  

Need fiberglass to make servos.  

Need plastic to make fiberglass.  

Um.

That's a problem that is not possible to overcome if you haven't already gotten an oil refinery up and running, pre-patch.

**Comment by springphul** [comment]
@ Developers. This Bug is an A-Bug. It prevents the player from getting further in the game. 
The play circle is not written correctly, but it serves the issue reporting.

Actually you need Electricity for the Pumpin Jack, for oil. Oil -> Epoxy -> Substrat -> PCB -> Electromotor/ Combustion Generator -> Electricity .. here we start again.

I don't understand, why you don't declare this bug as "Critical Priority". It is a game stopper, dead end or however you want to call it. It is like a game crash or freeze. You are not able to play the game.

**Comment by springphul** [comment]
@SnarkyBird can you probably please change the title to: 'Critical Bug: Game Broken due "Electricity is needed to produce Electricity - Loop" ' . Maybe the devs are understanding the impact easier?

**Comment by SnarkyBird** [comment]
It wasn't game-stopping on our server because a different player already had an oil refinery up and running before the patch, but your point still stands.

**Comment by springphul** [comment]
Ah I c. I understand. For me, playing solo and not having a combustion geny, it is game stoping ;-) And thx, considering my suggestion. I hope they fix it soon.
