### ISSUE TITLE
USER ISSUE: Growing Trees

### ISSUE THREAD

**Issue by BlazeGuy2** [StrangeLoopGames/EcoSuggestions#480]
_From @EiKiDa on July 24, 2018 14:3_

**Version:** 0.7.6.2 beta

**Steps to Reproduce:**
Trees are growing too slowly. 100-150 hours in real life whilst staying in game.

**Expected behavior:**
100-150 real life hours in and out game.

**Actual behavior:**
100-150 real life hours IN game.

_Copied from original issue: StrangeLoopGames/EcoIssues#8713_

**Comment by PacifyerGrey** [comment]
When playing on KatherineOfSky server we were experimenting on tree grouth times and found that halving them is a nice balance. So that Cedar trees grow 2 days till full maturity and Oaks do take 3. With this settings we could catch up with economy needs being able to regrow trees as they were consumed.

The real issue mostly hits single player where is makes near to no sense as trees do not grow while you are offline. The whole farming and forestry should be accelerated dramatically in single player in my opinion.

**Comment by elfl0rd** [comment]
@D3nnis3n can be closed due to sleep in game.

**Comment by D3nnis3n** [comment]
Tree growth time afaik can also be changed in the simulation config.

**Comment by elfl0rd** [comment]
ofc.
