### ISSUE TITLE
Allow admins to DELETE laws, not only repeal them

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#506]
I want to be able to delete laws from database, as some players found it funny to name laws by normal english words just for fun with a nonsense law inside. That leads to the chat being big bold and many words linked to a law. E.g. "What a nice day" - We got a law for what, one for nice and one for day. :/

**Comment by Deantwo** [comment]
You can use the `/clearlaws` admin command. But it remove all laws.
See: https://eco.gamepedia.com/Chat_Commands

**Comment by Deantwo** [comment]
I believe that you can also delete individual laws using the website. If you are admin there should be a delete button on the page of each law.

**Comment by D3nnis3n** [comment]
This feature only repeals them, but does not DELETE them.

**Comment by Deantwo** [comment]
Can you still referance/link to a repealed law?
Since they aren't showen on the website I assumed they were gone.

PS: Would be nice if we could see repealed laws, so we could see discussion on them and such for reference when proposing new laws. But yes, just make us unable to make chat links to repealed laws.

**Comment by D3nnis3n** [comment]
Yes, you can. But if you hover over it it just says "removed property", e.g. it does not even store the old laws for review. So keeping them is absolutley useless!

**Comment by D3nnis3n** [comment]
That's now possible.
