### ISSUE TITLE
Easy-on-the-eyes mode

### ISSUE THREAD

**Issue by MiteEnBois** [StrangeLoopGames/EcoSuggestions#511]
hello guys, i have some criticism to make. Not on the game itself but more on the artstyle. You see, i have a friend that gets sick when playing eco. He says that the extreme cubism and the flashy colors give him headaches and make him nauseous (he actually vomited once). So he would really want something to be fixed, or an option to help with his problems. He really want to play but the pain he endures is too much for it. So, do you have a solution already on hand that i don't know already, or do you know anything that can help? Thank you

**Comment by D3nnis3n** [comment]
Hello MiteEnBois,
while we try to offer the most common accessibility options and have already included Anti-Headbobbing and Arachnophobia mode in Update 9.0, we unfortunately cannot fix every problem a player could possibly have - this unfortunately is one of them due to amount of changes that would be required. I hope you can understand.
