### ISSUE TITLE
New Law Clause: Resident of District

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#514]
We want to go a bit federal and want laws that do only apply to citizens of specific districts. That means somewhat should track if someone has property or a house with at least value 0,1 in a district, and only then this law applies to him.

**Comment by D3nnis3n** [comment]
To expand on that, districts could have overlays, e.g. you can be in two districts at once. That'll allow the district tool for creating states and mark areas in this state, too. If one would really go in-depth, one probably could use titles to create states, that could be taxed by federal law - but the property claims may not be enough for this.

I'm in full knowledge that this probably will never get into the game or at least not too soon or with the titles update, but i just wanted to express interest in being able to create a fully fledged federal republic in the game that allows players to really decide on where to live in the world. Maybe one state has better laws for tailings, so smiths would probably go there. That simulates a bit more of the real world and - when seen as several countries on earth could be a good step to make the use of multiple currencies very fun, when people have to cross the borders for some trade. It'll also allow for more variety, when state laws are there.

**Comment by MarjieAVolk** [comment]
I like the idea of having conditions for residence.  I have thought about this before, but was always a little fuzzy on exactly how it would be computed.  Your suggestion of just requiring non-zero skill points seems good.  There might still be some other design concerns; For example, if you build a house that is in more than one district, that could potentially be an exploit.  Also it might be very easy to build a tiny house with value 0.1, and just go make yourself a resident everywhere, or temporarily make yourself a resident in order to vote on things.  Not sure if we should put in more safeguards for an official 'residency' value, or just throw it out there and let players create more safeguards themselves, eg. with demographics.

I might also suggest including more calculations having to do with housing points, eg. `If your housing value in 'Town' > 10`

As for supporting multiple governments, we would like to do this some day also, but it hasn't been prioritized by anyone yet.  What I've been suggesting, in regards to your overlapping districts request, is that there is a third 'government territory' sort of layer, which would behave more like property.  Governments would get 'territory claims' as they grow, allowing them to expand their borders.  Just one other idea.

**Comment by D3nnis3n** [comment]
Great you like that idea. If a house is in more than one district - which did indeed happen in Germany for some people, it does apply to the district most of the land is based on ore just by state decision - the latter probably would be hard to implement and not worth it while the first still has the problem of what happens when the house is distributed exactly evenly in both districts. I don't have a good idea to solve that at the moment, though.

Probably the government itself should deal with the negative things you've shown. Maybe even add a feature to chose residence when you plan on having a government layer.

The conditions for housing values would be a great start, though!

As for supporting multiple governments, that sounds great but the way at least we would want to do it is as in a federal republic. That does mean we do not want to have 12 autonoumous governments, but a federal government and several state ones that are limited in their actions. But surely, a multiple country world would be something that expands on the game, too. But you probably should be able to have a federal setting, too.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/872
