### ISSUE TITLE
Laws: Define something in a law to be used later

### ISSUE THREAD

**Issue by D3nnis3n** [StrangeLoopGames/EcoSuggestions#580]
I would love to define a category of things to use in other laws or at least the same.
E.g. i could efine Birch, Cedar, Fir and Oak to be "group: Trees" and could reference this group in other laws easily by just choosing "group: Trees". Would save so much time.

**Comment by MarjieAVolk** [comment]
Demographics are kind of a special case of this (that is, they let you save a category for later, but it can only be used for player conditions).

I am planning on adding a built in species group thing, that would handle this trees case.

So yeah, I am open to adding more things like this, but I just need to either nail down specifically which things need to be saved, or spend more time coming up with a more generic way to handle saving variables of any type.

**Comment by D3nnis3n** [comment]
Well, something you could specifiy yourself would be the best but most complex version.
We would use it for trees, for ALL plants and for categories of plants that we would define ourselves. E.g. we would categorize some plants to be a group, so we can issue laws on this group.

**Comment by MarjieAVolk** [comment]
I think for species groups, a set of hard coded species groups (eg. plants, animals, trees, shrubs, aquatic/terrestrial, etc) will solve most cases you're thinking of.  (See https://github.com/StrangeLoopGames/EcoIssues/issues/4088)

I suppose another direction we could take it though, would be to have conditions on the species, instead of or in addition to groups.  Eg. 'is a tree', 'population < 50'

**Comment by MarjieAVolk** [comment]
Oh yeah, see also https://github.com/StrangeLoopGames/EcoIssues/issues/8114

**Comment by MarjieAVolk** [comment]
So I think I will close this suggestion, as it is covered in those bugs already.
