### ISSUE TITLE
If lastseen > x; Then

### ISSUE THREAD

**Issue by Knigge** [StrangeLoopGames/EcoSuggestions#584]
I can not find this function in the law system now. This should be added to make more automated modifiers for players that join and then leave the server. Would be usefull for both claims, currency and a wast amount of laws.

**Comment by torchdragon** [comment]
Would it be better to have a float threshold of "recent active time" rather than just X days? I agree that last seen would be simpler, but would not address the condition of someone logging in once every other day to keep their claim up.

Having an activity percentage, particularly with dials that can be adjusted by server administrators would allow a much better level of detail that can be linked to laws.

**Comment by D3nnis3n** [comment]
Can be done already.
