### ISSUE TITLE
Storage management

### ISSUE THREAD

**Issue by colaxgutten** [StrangeLoopGames/EcoSuggestions#654]
This might be under same topic as "Storage Organization".
A set of options should be added to the storages and crafting tables:
- Item filters for storages would be 
  nice, like a list of items which it can accept or a list of items to exclude. It might be included to a more 
  advanced storage item of some sort, maybe tier 2 materials or something.
- Input and output storages for crafting tables so you can make products go to one storage and 
  resources come from another storage.
- The storage settings should be the same for everyone in the deed or with the same access to a crafting 
  table such that if I change what storages a crafting table can access, these settings will be the same for 
  my friends.

**Comment by ClDumbass** [comment]
The input/output thing would be a life-saver for me setting up auto-crafting stores.

**Comment by FireByTrial** [comment]
the ability to have more than just the enable disable on a linked storage would be awesome, something as simple as an enable pull and enable push (deliver?) checkbox would be amazing! something like this (but inline) on the linked storage would be so nice (defaulted on of course)
```
[✔] enable | [ ] pull | [✔] deliver
```
would allow us to easily have limits on production so if you accidentally produce too much of something you don't end up filling all your storage and having to play storage Tetris.

If there were a way to set a filter or whitelist on a storage location that would also be awesome. like say a storage chest can only contain seeds or a certain stockpile can only store sand etc

**Comment by ThibautSF** [comment]
I would add some info/ideas for storage filters : 
- it could be in and out filters -> ie allows dirt and sand to be added in a stockpile, but only allow dirt to be removed (maybe limited to "automatically" like for a craft project -> the craft project won't have the right to get dirt from that stockpile)
- the "out" filter is a bit like the idea mentioned before (comes from #396) but maybe in a more extendable way
- A filter could be based on specific items or group of items (I don't know if there are item's tags in the game, like "fuel" for all (fuel type)[https://eco.gamepedia.com/Power#Fuel_Types]). Default would be "allow all / exclude none"

Extendable?
- filters could be dependent on users or ranks -> ie allows citizens to put dirt and sand, but only allow a specific user to get the dirt and sand

About UI:
- All of this could use interfaces similar to existing ones.
- For storage UI, button(s) to open "in filter" and "out filter" (or list of filters with add/remove option in the extension idea case)
- The interface for filter could be similar to properties permissions, but instead of adding players or groups of players, it adds items or group of items

**Comment by Conchipedia** [comment]
**maybe something like this?**

![36458962-5c506a8a-16a9-11e8-804e-27c47da9a226](https://user-images.githubusercontent.com/29383891/91781895-745c2e80-ebf3-11ea-8881-36ee7ff2f3f5.png)
![36458965-6123d862-16a9-11e8-9ce3-52d1b577f3c0](https://user-images.githubusercontent.com/29383891/91781899-758d5b80-ebf3-11ea-85ba-7008d9ae2c68.png)
![36458972-68838210-16a9-11e8-8fe3-05c39c70b6b6](https://user-images.githubusercontent.com/29383891/91781900-7625f200-ebf3-11ea-9a01-3800bfb3cf81.png)

this will give us infinite possibilities especially seeing as we can already sort the storage in whichever order we want them to access first.

**Comment by ikiris** [comment]
Ideally, the ability to filter where multiple outputs go by stockpile. Like taillings in this one, iron in this other one. That would make things MUCH more managable.

**Comment by ShoppyCodes** [comment]
Not sure if this requires it's own issue but it would also be useful if we could do direct machine output to machine input

**Comment by ThePiachu** [comment]
It would also be nice to have some in-stockpile filters, similarly to what you can do in Factorio or Terraria - you can specify what item can go in a given slot and that's the only item that goes into that slot, reserving space for it even if the storage is empty.

**Comment by D3nnis3n** [comment]
Merged with https://github.com/StrangeLoopGames/EcoSuggestions/issues/1570
