### ISSUE TITLE
Cycling buildables by tapping SHIFT or CTRL+SHIFT 

### ISSUE THREAD

**Issue by jellomold** [StrangeLoopGames/EcoSuggestions#689]
Currently if you press and hold SHIFT, you cycle buildables (eg hewn logs) with the scroll wheel. it's a bit finicky.  I regularly overshoot and the visual contrast between selected and not is sometimes indistinct.

perhaps a controls toggle to enable "shift tapping".  meaning when you have a buildable, you simply TAP shift to cycle to the next "type" ... (eg floor -> wall -> block -> roof -> window... etc) 

CTRL+SHIFT tap cycles in reverse.

**Comment by D3nnis3n** [comment]
Hello jellomold,
thanks for your suggestion, really appreciated.

In Update 9.0 with the addition of a lot of new building blocks we now have a menu that lists all the blocks in a specific category. Because of this, your suggestion is no longer applicable (as the menu you are talking about does no longer exist), so i'm going to close it.

I hope the new system will work well for you :)
