### ISSUE TITLE
Limit Maximum Jobs Per Table

### ISSUE THREAD

**Issue by WeaselDog** [StrangeLoopGames/EcoSuggestions#747]
Currently the maximum amount of jobs is 50,000. People are using this to exploit:

Have someone with specialization come queue 50,000 jobs and you have that specialization essentially forever. It makes some things like Glassworking and Lumber useless once someone has done this. I have seen it done by multiple people to get an unfair advantage. 

I don't see any reason why the maximum queue should be over 1,000; even that seems like too much. Why not 100 per stack, for a total of 500?

**Comment by johnkslg** [comment]
I like this, we'll be making changes here.

**Comment by ClDumbass** [comment]
I assume you mean the amount on a single job (e.g. one job asking to craft lumber 9999 times), rather than the number of different jobs which already seems to be limited to 5. 

If the goal is to prevent people from having the job forever, then perhaps it would be best to simply deactivate jobs if the player has been offline for more than a set time, e.g. 24-48h. As it is I set jobs like this not so I can avoid playing, but so I don't have to run back and forth on menial tasks to help others. 

I think the jobs should also have a deliberate perpetual mode (assuming an offline limit is in place first) where the quantity is the number they want to see in their output storage rather than the number to make total. Once that amount is reached they paused, but then start again when the number drops too low.

If you do both of the above then it would be perfectly reasonable to limit jobs to something in the low hundreds, or even 100.

**Comment by Praefator** [comment]
I don't think just 5x 100 is enough. I frequently queue up multiple hundreds of concrete in my cement kilns linked to my store, so that whenever people sell me granite and gneiss, concrete resumes being poured out. Given how much asphalt our city tends to use at any given map this change would hamstring us greatly. 

Perhaps a compromise can be reached in making it configurable through the Server UI, e.g. a MaxNumOfQueueObjects or something?

**Comment by Guedez** [comment]
That's a very hard problem to solve
If people want to make themselves obsolete, why shouldn't them?
Because they will make other people on the same professions obsolete too?
Well, they can do that without using this feature to begin with by selling all items at cost price on their store and buying all ingredients

**Comment by Blanclour** [comment]
The only way to truly solve this is to attach some kind of value to the crafting process to ensure it isn't used carelessly. Materials don't matter since people can simply put up a buy order for the required materials no matter how expensive and auto craft them into a product for sale.

Something that cannot be replaced is the player's time. If time or dedication is attached then the player will take it seriously. At the same time it shouldn't be more meticulous then it has to be.

Making it so that players must be within a certain range of the table in order for it to continue crafting seems like an appropriate trade-off. Perhaps make it so that it continues to craft after the player has left the radius for a certain amount of time before actually halting production. This shouldn't apply to all tables, only the tables or recipes that are prone to excessive auto-crafting such as hewing, mortaring, smelting, lumber, bricks, cement, rolling mills, glass, ect.

In most cases I don't see this significantly breaking any game play since most people have all their personal tables close together. Queuing up a friend's table would require the active maintenance of returning to the table's radius to resume production, making it less likely for people to commit to a queue they don't want to babysit.

People who make raw conversion shops would have to actively maintain the queue by staying near it rather then logging off and effectively ruining competing player's chances to make money on the specified item. This also helps to promote more then one player having the same skill, since a player can only craft said items when they are online and attentive it would give others a chance to conduct business even if their efficiency is less.

**Comment by WeaselDog** [comment]
Closing due to upcoming changes to crafting
