### ISSUE TITLE
Too much smelting/item costs

### ISSUE THREAD

**Issue by trevelmike** [StrangeLoopGames/EcoSuggestions#757]
As i mentioned in a previous post, the item costs for certain products esp steel,rebar, lumber into charcoal etc are simply too much. 200 iron ores get me 100 iron bars, out of that i get maybe 60 steel and 40 or so rebar. Rebar esp should be a 1 to 1 ratio of steel none of this two. Obviously the main problem is because we have to use  reinforced concrete until we get the steel mill or w/e it is to make tier 3 foundation. It just leads to more and more air pollution. 

I would switch to charcoal but again charcoal takes too much lumber to make. I am not cutting down entire forests just make a mere amount of charcoal.

**Comment by Guedez** [comment]
You can actually just use reinforeced glass or whatever was the name. It's Tier 4
Make a cheese house with it.
I think you need 141 of a material for a 150 space cheesehouse. It's been very long since I last calculated
It was certainly enough to put about 4 workbenches
If I remember correctly it's 5x5 (25 floor + 25 ceiling) and 12 blocks per height (1 0 1 0 1x4 per wall)
You can make it 5 wide 5 forward and 7 tall for 175 space with some left over, but I think some particularities of how doors/windows made so that you could only make it 6 tall for 150 space

Sure the costs are pretty big, but that's probably because they balanced the game assuming that the 10% cheaper talent would actually work, this would actually double the efficiency of everything

**Comment by D3nnis3n** [comment]
You can configure this in your server files. 9.0 will also have a global resource modifier you can use.
