### ISSUE TITLE
Claim Restitution for Deserter

### ISSUE THREAD

**Issue by Cyclesim** [StrangeLoopGames/EcoSuggestions#844]
When your claims have been removed by a deserter law they would automatically be replaced in your inventory.  This way if you choose to come back to the server you can start over.  I and many others had our claims removed on SLG's Giant Tortoise server when the definition of deserter was changed from 6 days to 1 day.

**Comment by D3nnis3n** [comment]
Instead of removing claims they can now be seized, so government can keep them and reissue them when you come back (or even give you back your plot if it hasn't been used yet). This is not automatic, but generally deserters rarely come back and giving back claims can also be exploited.

As claims will be no longer limited by skills and distributed by governments in the future, it makes no sense to implement this exact suggestion, so i'm closing this. It shouldn't be an issue anymore anyway :)
